### PR TITLE
Update all libraries and migrated to octane

### LINKED ISSUE #39: Is this maintained?
@safeforge @algodave

### PR DESCRIPTION
**Pull request by sinankeskin**
It was a really big update but I couldn't split into 2 PRs, sorry. Fixes #39

In summary;

- All libraries except ember-cli-mirage updated to latest version. There is an active bug in ember-cli-mirage. Don't update.
- Addon migrated to octane.
- All classes coverted to native classes.
- README examples updated to octane.
- ember-active-storage config added to ENV. For now, it has only url parameter.
- With env config help, users don't need to pass url explicitly now.
- 'loadstart', 'load', 'loadend', 'error', 'abort', 'timeout' events added and invokes onLoadstart, onLoad, onLoadend, onError, onAbort, onTimeout accordingly.
- Some new events tests added.
- All tests updated and all green hopefully.
- cached decorator added for performance reason.

I've tested with my production app and transition was flawless for me.

It was a pleasure. Thank you.

### CODE REVIEW

**Comment by sinankeskin** [comment]
All green. Great.

https://travis-ci.org/github/algonauti/ember-active-storage/builds/759240026

**Comment by safeforge** [comment]
@sinankeskin thank you for your effort, also because we're addressing the #16 with events support, really appreciated!

My only concern is about the migration from `yarn` to `npm`, actually the repository contains both `yarn.lock` and `package-lock.json` and I think we need to take a decision in order to avoid bugs and confusion during development.

I prefer to continue to use yarn just because all ember's projects still using it, as you can see at [ember-cli](https://github.com/ember-cli/ember-cli), [ember.js](https://github.com/emberjs/ember.js) and [data](https://github.com/emberjs/data). What’s your opinion on that?

**Comment by sinankeskin** [comment]
It's ok. Even better, we can add lock files to .gitignore. That way users can choose whatever they want.

I guess package.json is suffice, no need to lock files. Also travis-ci runs all tests with yarn --no-lockfile option.

**Comment by safeforge** [comment]
I don't think it's a good idea, `*.lock` permits to test the library with specific version of dependencies and avoid the scenario where each developer has his own version. We just need to define our package manager. 

Since ember member seems to prefer `yarn` over `npm` ([ember-classic-decorator](https://github.com/emberjs/ember-classic-decorator) is another example) - I suggest to continue to use yarn.

**Comment by sinankeskin** [comment]
I guess it's ok now.

**Comment by safeforge** [comment]
I think before to merge we need to fix also 
```
* .travis.yml
* config/ember-try.js
* tests/dummy/config/ember-cli-update.json
```

with the current changes 

```patch
diff --git a/.travis.yml b/.travis.yml
index 156fd25..3a7ed03 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -11,8 +11,7 @@ addons:
   chrome: stable
 
 cache:
-  directories:
-    - $HOME/.npm
+  yarn: true
 
 env:
   global:
@@ -35,15 +34,15 @@ jobs:
     - stage: "Tests"
       name: "Tests"
       script:
-        - npm run lint
-        - npm run test:ember
+        - yarn lint
+        - yarn test:ember
 
     - stage: "Additional Tests"
       name: "Floating Dependencies"
       install:
-        - npm install --no-package-lock
+        - yarn install --no-lockfile --non-interactive
       script:
-        - npm run test:ember
+        - yarn test:ember
 
     # we recommend new addons test the current and previous LTS
     # as well as latest stable release (bonus points to beta/canary)
@@ -55,5 +54,9 @@ jobs:
     - env: EMBER_TRY_SCENARIO=ember-default-with-jquery
     - env: EMBER_TRY_SCENARIO=ember-classic
 
+before_install:
+  - curl -o- -L https://yarnpkg.com/install.sh | bash
+  - export PATH=$HOME/.yarn/bin:$PATH
+
 script:
   - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO
diff --git a/config/ember-try.js b/config/ember-try.js
index e59f91b..f14ac7f 100644
--- a/config/ember-try.js
+++ b/config/ember-try.js
@@ -4,6 +4,7 @@ const getChannelURL = require('ember-source-channel-url');
 
 module.exports = async function () {
   return {
+    useYarn: true,
     scenarios: [
       {
         name: 'ember-lts-3.16',
diff --git a/tests/dummy/config/ember-cli-update.json b/tests/dummy/config/ember-cli-update.json
index 23496a1..49a31c5 100644
--- a/tests/dummy/config/ember-cli-update.json
+++ b/tests/dummy/config/ember-cli-update.json
@@ -9,7 +9,10 @@
           "name": "addon",
           "outputRepo": "https://github.com/ember-cli/ember-addon-output",
           "codemodsSource": "ember-addon-codemods-manifest@1",
-          "isBaseBlueprint": true
+          "isBaseBlueprint": true,
+          "options": [
+            "--yarn"
+          ]
         }
       ]
     }

```

**Comment by sinankeskin** [comment]
You are right. Done.

Lets wait travis to finish all with green.

**Comment by sinankeskin** [comment]
All green.

https://travis-ci.org/github/algonauti/ember-active-storage/builds/759515142

**Comment by safeforge** [comment]
@sinankeskin I just tested the dummy application and received an error in console, I'll check tomorrow in my morning and provide you more details if you aren't able to reproduce. 

Screenshot 2021-02-18 at 20 43 41

**Comment by sinankeskin** [comment]
It's ok. Fixed now. There is no get function on octane.

**Comment by safeforge** [comment]
@sinankeskin LGTM, thank you again for the support, I'll test on master with the goal to release a new version in the next days.

**Comment by safeforge** [comment]
> There is an active bug in ember-cli-mirage. Don't update.

@sinankeskin do you have a link which describes the bug?

**Comment by sinankeskin** [comment]
No. I found it but I couldn't find the issue about that.

If I have to describe, basically mirage intercepts the sample.pdf request and changes the bytesize of the request and this makes some test failed. With latest version also you have to add this.passthrough('/sample.pdf') to config.

Please try yourself. Maybe I'm missing something.

**Pull request merged**
