### PR TITLE
Update for latest change requests

### PR DESCRIPTION
**Pull request by sinankeskin**
Fixes both #54 and #55

### CODE REVIEW

**Comment by fsmanuel** [comment]
@sinankeskin Thanks! Is it already released?

**Comment by sinankeskin** [comment]
> @sinankeskin Thanks! Is it already released?

Yes. You can use.

**Comment by fsmanuel** [comment]
@sinankeskin what is the latest release version?
npm states 2.1.1 Published 9 months ago as the latest. Would be great to have a release on npm with this changes.

**Comment by sinankeskin** [comment]
Oh one second. I think we forgot to release this as a package. I'll ping @safeforge to release. Thanks for the warning.

**Comment by safeforge** [comment]
version `2.2.0` is available on the registry. 💪

**Pull request merged**
