### PR TITLE
Update ember-cli version and some dependencies

### PR DESCRIPTION
**Pull request by sinankeskin**
Also could you please release a npm package after tests passed? @safeforge 

Thank you.

### CODE REVIEW

**Comment by safeforge** [comment]
@sinankeskin thank you for your support! About the new version I think it's time to release a new minor version `1.1.0`

**Comment by sinankeskin** [comment]
Actually it's a breaking changes. Minimum nodejs and emberjs version dramatically increased.

That's why in my opinion it's a v2.0 candidate.

**Comment by brunoocasali** [comment]
@safeforge can I help in something to get the new release (v2) done? 

(I'm currently pointing to master 😝 of this repo to get rid of the old deps)

**Comment by safeforge** [comment]
@brunoocasali  the new version is available under the `@algonauti` organization please  rename package's name `@algonauti/ember-active-storage`

**Comment by brunoocasali** [comment]
Wow!! This kind of change bites me everytime haha, thanks for this library!

**Pull request merged**
